/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type BaseUnitType = "KG" | "LITRE" | "METRE" | "PIECE";

export type CreditLedgerEntryType = "PAYMENT_RECEIVED" | "REFUND_ADJUSTMENT" | "SALE_ON_CREDIT";

export type CustomerType = "B2B_CONTRACTOR" | "RETAIL";

export type ExpenseStatus = "APPROVED" | "PENDING" | "REJECTED";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type InvoiceStatus = "DRAFT" | "FINAL" | "VOID";

export type InvoiceType = "GST" | "NON_GST";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LoyaltyTxnType = "EARN" | "EXPIRE" | "REDEEM" | "RESTORE" | "REVOKE";

export type Numeric = ColumnType<string, number | string, number | string>;

export type PaymentMethod = "CARD" | "CASH" | "CREDIT" | "LOYALTY_POINTS" | "UPI";

export type PoStatus = "CANCELLED" | "DRAFT" | "PARTIALLY_RECEIVED" | "RECEIVED" | "SENT";

export type PriceType = "TAX_EXCLUSIVE" | "TAX_INCLUSIVE";

export type QuotationStatus = "APPROVED" | "CANCELLED" | "CONVERTED" | "DRAFT" | "EXPIRED";

export type ReturnLineCondition = "DAMAGED" | "RESELLABLE";

export type SerialStatus = "IN_STOCK" | "RETURNED" | "SOLD" | "WARRANTY_CLAIM" | "WRITTEN_OFF";

export type StockMovementType = "COUNT_ADJUSTMENT" | "PURCHASE" | "PURCHASE_RETURN" | "RESERVATION" | "RESERVATION_RELEASE" | "SALE" | "SALE_RETURN" | "TRANSFER_IN" | "TRANSFER_OUT" | "WRITE_OFF";

export type TillEventType = "CASH_DROP" | "CASH_SALE" | "CLOSING_COUNT" | "PETTY_EXPENSE_PAYOUT";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TransferStatus = "CLOSED" | "DISPATCHED" | "RECEIVED" | "REQUESTED" | "TRANSFER_DISCREPANCY";

export type UserRole = "ACCOUNTANT" | "BRANCH_MANAGER" | "CASHIER" | "INVENTORY_STAFF" | "OWNER_ADMIN";

export type VendorLedgerEntryType = "DEBIT_NOTE" | "GRN_PAYABLE" | "PAYMENT_MADE";

export type WarrantyClaimStatus = "OPEN" | "REFUNDED" | "REJECTED" | "REPAIRED" | "REPLACED" | "SENT_TO_VENDOR";

export interface AdminSettings {
  branch_id: string | null;
  setting_id: Generated<string>;
  setting_key: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  value: Json;
}

export interface Attendance {
  check_in: Timestamp | null;
  check_out: Timestamp | null;
  employee_id: string;
  id: Generated<string>;
  method: Generated<string>;
  work_date: Timestamp;
}

export interface AuditLog {
  action: string;
  audit_id: Generated<string>;
  branch_id: string | null;
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string;
  new_value: Json | null;
  old_value: Json | null;
  user_id: string | null;
}

export interface Backups {
  backup_id: Generated<string>;
  restore_tested_at: Timestamp | null;
  status: Generated<string>;
  storage_ref: string;
  taken_at: Generated<Timestamp>;
}

export interface Branches {
  address: string | null;
  branch_id: Generated<string>;
  created_at: Generated<Timestamp>;
  gstin: string | null;
  is_active: Generated<boolean>;
  name: string;
  phone: string | null;
  state_code: string;
}

export interface BranchStock {
  base_unit_qty: Generated<Numeric>;
  branch_id: string;
  product_id: string;
  reorder_max: Numeric | null;
  reorder_min: Numeric | null;
  reserved_qty: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  weighted_avg_cost: Generated<Numeric>;
}

export interface Brands {
  brand_id: Generated<string>;
  name: string;
}

export interface BundleItems {
  bundle_id: string;
  product_id: string;
  qty_base_unit: Numeric;
}

export interface Bundles {
  bundle_id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
}

export interface Categories {
  category_id: Generated<string>;
  name: string;
  parent_category_id: string | null;
}

export interface CreditNoteLines {
  cgst_amount: Generated<Numeric>;
  credit_note_id: string;
  id: Generated<string>;
  igst_amount: Generated<Numeric>;
  invoice_line_id: string;
  line_total: Generated<Numeric | null>;
  qty_base_unit: Numeric;
  sgst_amount: Generated<Numeric>;
  taxable_value: Numeric;
}

export interface CreditNotes {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  credit_note_id: Generated<string>;
  credit_note_number: string;
  invoice_id: string;
  reason: string;
  total_amount: Generated<Numeric>;
}

export interface CustomerCreditCache {
  cached_at: Timestamp;
  cached_balance_owed: Numeric;
  cached_credit_limit: Numeric;
  customer_id: string;
}

export interface CustomerCreditLedger {
  amount: Numeric;
  balance_after: Numeric;
  branch_id: string | null;
  created_at: Generated<Timestamp>;
  customer_id: string;
  entry_id: Generated<string>;
  entry_type: CreditLedgerEntryType;
  ref_id: string | null;
  ref_table: string | null;
}

export interface CustomerMergeLog {
  id: Generated<string>;
  merged_at: Generated<Timestamp>;
  merged_by: string | null;
  merged_customer_id: string;
  primary_customer_id: string;
}

export interface Customers {
  created_at: Generated<Timestamp>;
  credit_allowed: Generated<boolean>;
  credit_limit: Generated<Numeric>;
  customer_id: Generated<string>;
  customer_type: Generated<CustomerType>;
  dob: Timestamp | null;
  email: string | null;
  gstin: string | null;
  loyalty_points_balance: Generated<number>;
  name: string;
  phone: string;
}

export interface DeliveryChallanLines {
  challan_id: string;
  id: Generated<string>;
  product_id: string;
  qty_base_unit: Numeric;
}

export interface DeliveryChallans {
  branch_id: string;
  challan_id: Generated<string>;
  challan_number: string;
  created_at: Generated<Timestamp>;
  customer_id: string;
  quotation_id: string | null;
  status: Generated<string>;
}

export interface DocumentSequences {
  branch_id: string;
  fiscal_year: string;
  last_number: Generated<Int8>;
  prefix: string;
  series: string;
}

export interface Employees {
  branch_id: string;
  designation: string | null;
  employee_id: Generated<string>;
  joined_at: Generated<Timestamp>;
  user_id: string;
}

export interface EmployeeShifts {
  employee_id: string;
  id: Generated<string>;
  shift_id: string;
  work_date: Timestamp;
}

export interface ExpenseCategories {
  category_id: Generated<string>;
  name: string;
}

export interface Expenses {
  amount: Numeric;
  approved_by: string | null;
  branch_id: string;
  category_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  expense_id: Generated<string>;
  paid_from_till_session_id: string | null;
  receipt_url: string | null;
  status: Generated<ExpenseStatus>;
}

export interface Grn {
  branch_id: string;
  created_by: string | null;
  grn_id: Generated<string>;
  grn_number: string;
  po_id: string | null;
  received_at: Generated<Timestamp>;
  vendor_id: string;
}

export interface GrnLines {
  batch_id: string | null;
  grn_id: string;
  grn_line_id: Generated<string>;
  product_id: string;
  qty_base_unit: Numeric;
  rate: Numeric;
}

export interface HsnTaxRates {
  cess_rate_pct: Generated<Numeric>;
  effective_from: Timestamp;
  effective_to: Timestamp | null;
  gst_rate_pct: Numeric;
  hsn_code: string;
  hsn_tax_rate_id: Generated<string>;
}

export interface InvoiceLines {
  base_unit_qty: Numeric;
  batch_id: string | null;
  cgst_amount: Generated<Numeric>;
  discount_amount: Generated<Numeric>;
  igst_amount: Generated<Numeric>;
  invoice_id: string;
  line_id: Generated<string>;
  line_total: Generated<Numeric | null>;
  price_type: PriceType;
  product_id: string;
  product_unit_id: string | null;
  qty_in_sale_unit: Numeric;
  rate_locked_at_scan: Numeric;
  sgst_amount: Generated<Numeric>;
  taxable_value: Numeric;
}

export interface InvoicePayments {
  amount: Numeric;
  invoice_id: string;
  method: PaymentMethod;
  payment_id: Generated<string>;
  ref_no: string | null;
}

export interface Invoices {
  branch_id: string;
  cgst_total: Generated<Numeric>;
  client_txn_id: string | null;
  conflict_resolved_by: string | null;
  created_by: string | null;
  customer_id: string | null;
  device_created_at: Timestamp;
  discount_total: Generated<Numeric>;
  grand_total: Numeric;
  igst_total: Generated<Numeric>;
  invoice_id: Generated<string>;
  invoice_number: string | null;
  invoice_type: InvoiceType;
  irn: string | null;
  is_offline_conflict: Generated<boolean>;
  place_of_supply_state_code: string | null;
  round_off: Generated<Numeric>;
  server_received_at: Generated<Timestamp>;
  sgst_total: Generated<Numeric>;
  sold_by_employee_id: string | null;
  status: Generated<InvoiceStatus>;
  subtotal: Numeric;
  till_session_id: string | null;
}

export interface LeaveRequests {
  approved_by: string | null;
  employee_id: string;
  from_date: Timestamp;
  id: Generated<string>;
  status: Generated<string>;
  to_date: Timestamp;
}

export interface LoginAttempts {
  attempted_at: Generated<Timestamp>;
  id: Generated<string>;
  identifier: string;
  ip_address: string | null;
  succeeded: boolean;
}

export interface LoyaltyTransactions {
  balance_after: number;
  created_at: Generated<Timestamp>;
  customer_id: string;
  id: Generated<string>;
  invoice_id: string | null;
  points: number;
  sales_return_id: string | null;
  txn_type: LoyaltyTxnType;
}

export interface MarketingCampaigns {
  campaign_id: Generated<string>;
  campaign_type: string;
  created_by: string | null;
  message_template: string;
  name: string;
  scheduled_at: Timestamp | null;
  segment_query: Json | null;
}

export interface OtpRequests {
  attempts: Generated<number>;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  otp_hash: string;
  otp_id: Generated<string>;
  phone: string;
  purpose: Generated<string>;
}

export interface PaintTintRecords {
  base_shade: string | null;
  id: Generated<string>;
  invoice_line_id: string;
  notes: string | null;
  tint_formula: string | null;
}

export interface PasswordResetTokens {
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  reset_id: Generated<string>;
  reset_kind: Generated<string>;
  token_hash: string;
  user_id: string;
}

export interface PayrollEntries {
  base_salary: Numeric;
  deductions: Generated<Numeric>;
  employee_id: string;
  id: Generated<string>;
  incentives: Generated<Numeric>;
  net_pay: Numeric;
  pay_month: Timestamp;
}

export interface ProductBarcodes {
  barcode: string;
  barcode_id: Generated<string>;
  is_internally_generated: Generated<boolean>;
  product_id: string;
  product_unit_id: string | null;
}

export interface ProductPrices {
  branch_id: string | null;
  created_by: string | null;
  effective_from: Generated<Timestamp>;
  effective_to: Timestamp | null;
  mrp: Numeric;
  price_id: Generated<string>;
  product_id: string;
  selling_price: Numeric;
}

export interface Products {
  base_unit: BaseUnitType;
  batch_tracked: Generated<boolean>;
  brand_id: string | null;
  category_id: string | null;
  created_at: Generated<Timestamp>;
  default_price_type: Generated<PriceType>;
  hsn_code: string;
  image_url: string | null;
  is_active: Generated<boolean>;
  name: string;
  product_id: Generated<string>;
  reference_purchase_price: Numeric | null;
  serial_tracked: Generated<boolean>;
  sku: string;
  spec: Json | null;
}

export interface ProductUnits {
  is_default_sale_unit: Generated<boolean>;
  multiplier_to_base: Numeric;
  product_id: string;
  product_unit_id: Generated<string>;
  unit_label: string;
}

export interface PurchaseOrderLines {
  po_id: string;
  po_line_id: Generated<string>;
  product_id: string;
  qty_base_unit: Numeric;
  rate: Numeric;
}

export interface PurchaseOrders {
  branch_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  po_id: Generated<string>;
  po_number: string;
  status: Generated<PoStatus>;
  vendor_id: string;
}

export interface QuotationLines {
  line_id: Generated<string>;
  product_id: string;
  qty_base_unit: Numeric;
  quotation_id: string;
  rate: Numeric;
}

export interface Quotations {
  branch_id: string;
  converted_invoice_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  price_type: Generated<PriceType>;
  quotation_id: Generated<string>;
  quotation_number: string;
  reservation_hold_until: Timestamp | null;
  status: Generated<QuotationStatus>;
  stock_reserved: Generated<boolean>;
}

export interface RegistrationRequests {
  created_at: Generated<Timestamp>;
  created_user_id: string | null;
  email: string | null;
  full_name: string;
  password_hash: string | null;
  phone: string;
  reject_reason: string | null;
  request_id: Generated<string>;
  requested_branch_id: string | null;
  requested_role: UserRole;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  status: Generated<string>;
}

export interface ReturnWindows {
  category_id: string;
  window_days: number;
}

export interface SalesReturnLines {
  cash_refund_amount: Generated<Numeric>;
  condition: ReturnLineCondition;
  id: Generated<string>;
  invoice_line_id: string;
  points_earned_reversed: Generated<number>;
  points_redeemed_restored: Generated<number>;
  qty_base_unit: Numeric;
  return_id: string;
}

export interface SalesReturns {
  branch_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  credit_note_id: string | null;
  invoice_id: string;
  refund_method: PaymentMethod | null;
  refund_total: Generated<Numeric>;
  return_id: Generated<string>;
  return_reason: string | null;
  store_credit_total: Generated<Numeric>;
}

export interface Shifts {
  branch_id: string;
  end_time: string;
  name: string;
  shift_id: Generated<string>;
  start_time: string;
}

export interface StockAuditLines {
  audit_id: string;
  counted_qty: Numeric;
  id: Generated<string>;
  product_id: string;
  system_qty: Numeric;
  variance_qty: Generated<Numeric | null>;
}

export interface StockAudits {
  audit_id: Generated<string>;
  branch_id: string;
  completed_at: Timestamp | null;
  created_by: string | null;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface StockBatches {
  batch_id: Generated<string>;
  batch_number: string;
  branch_id: string;
  expiry_date: Timestamp | null;
  mfg_date: Timestamp | null;
  product_id: string;
  qty_remaining: Generated<Numeric>;
}

export interface StockConflicts {
  available_qty: Numeric;
  branch_id: string;
  conflict_id: Generated<string>;
  created_at: Generated<Timestamp>;
  invoice_id: string;
  product_id: string;
  requested_qty: Numeric;
  resolution: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  status: Generated<string>;
}

export interface StockLedger {
  base_unit_qty_change: Numeric;
  branch_id: string;
  cost_at_movement: Numeric | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  ledger_id: Generated<string>;
  movement_type: StockMovementType;
  product_id: string;
  reason_code: string | null;
  ref_id: string;
  ref_table: string;
}

export interface StockSerials {
  branch_id: string;
  invoice_line_id: string | null;
  product_id: string;
  serial_id: Generated<string>;
  serial_number: string;
  status: Generated<SerialStatus>;
}

export interface StockTransferLines {
  discrepancy_qty: Generated<Numeric | null>;
  dispatched_qty: Numeric;
  line_id: Generated<string>;
  product_id: string;
  received_qty: Numeric | null;
  resolution: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  transfer_id: string;
}

export interface StockTransfers {
  closed_at: Timestamp | null;
  dispatched_at: Timestamp | null;
  driver_ref: string | null;
  from_branch_id: string;
  received_at: Timestamp | null;
  requested_by: string | null;
  status: Generated<TransferStatus>;
  to_branch_id: string;
  transfer_doc_type: Generated<string>;
  transfer_id: Generated<string>;
}

export interface StockWriteoffs {
  branch_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  product_id: string;
  qty_base_unit: Numeric;
  reason_code: string;
  ref_transfer_line_id: string | null;
  writeoff_id: Generated<string>;
}

export interface TillEvents {
  acknowledged_by: string | null;
  amount: Numeric;
  created_at: Generated<Timestamp>;
  event_id: Generated<string>;
  event_type: TillEventType;
  note: string | null;
  ref_id: string | null;
  ref_table: string | null;
  session_id: string;
}

export interface TillSessions {
  branch_id: string;
  cashier_user_id: string;
  closed_at: Timestamp | null;
  closing_counted_cash: Numeric | null;
  counter_id: string;
  opened_at: Generated<Timestamp>;
  opening_float: Numeric;
  session_id: Generated<string>;
  status: Generated<string>;
}

export interface TrainingJournals {
  content_url: string;
  journal_id: Generated<string>;
  journal_type: string;
  language: string;
  published_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Users {
  branch_id: string | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  failed_attempts: Generated<number>;
  full_name: string;
  google_sub: string | null;
  is_active: Generated<boolean>;
  language_pref: Generated<string>;
  last_login_at: Timestamp | null;
  locked_until: Timestamp | null;
  must_change_password: Generated<boolean>;
  password_hash: string | null;
  phone: string | null;
  pin_hash: string | null;
  role: UserRole;
  user_id: Generated<string>;
}

export interface UserSessions {
  branch_id: string | null;
  created_at: Generated<Timestamp>;
  device_id: string | null;
  expires_at: Timestamp;
  ip_address: string | null;
  last_seen_at: Generated<Timestamp>;
  login_method: string;
  revoked_at: Timestamp | null;
  session_id: Generated<string>;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface VendorDebitNoteLines {
  debit_note_id: string;
  grn_line_id: string;
  id: Generated<string>;
  qty_base_unit: Numeric;
  rate: Numeric;
}

export interface VendorDebitNotes {
  branch_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  debit_note_id: Generated<string>;
  debit_note_number: string;
  grn_id: string;
  reason: string;
  total_amount: Numeric;
  vendor_id: string;
}

export interface VendorLedger {
  amount: Numeric;
  balance_after: Numeric;
  branch_id: string | null;
  created_at: Generated<Timestamp>;
  entry_id: Generated<string>;
  entry_type: VendorLedgerEntryType;
  ref_id: string | null;
  ref_table: string | null;
  vendor_id: string;
}

export interface VendorProductMap {
  is_preferred: Generated<boolean>;
  last_purchase_rate: Numeric | null;
  product_id: string;
  vendor_id: string;
  vendor_sku: string | null;
}

export interface Vendors {
  address: string | null;
  gstin: string | null;
  is_active: Generated<boolean>;
  name: string;
  payment_terms_days: number | null;
  phone: string | null;
  vendor_id: Generated<string>;
}

export interface Warranties {
  category_id: string | null;
  duration_months: number;
  product_id: string | null;
  warranty_id: Generated<string>;
}

export interface WarrantyClaims {
  claim_date: Generated<Timestamp>;
  claim_id: Generated<string>;
  invoice_line_id: string;
  resolved_at: Timestamp | null;
  rma_number: string | null;
  serial_id: string | null;
  status: Generated<WarrantyClaimStatus>;
  vendor_id: string | null;
}

export interface WhatsappMessageLog {
  attempts: Generated<number>;
  body: string | null;
  campaign_id: string | null;
  customer_id: string | null;
  id: Generated<string>;
  invoice_id: string | null;
  last_error: string | null;
  message_type: string;
  queued_at: Generated<Timestamp>;
  sent_at: Timestamp | null;
  status: Generated<string>;
  to_phone: string;
}

export interface DB {
  admin_settings: AdminSettings;
  attendance: Attendance;
  audit_log: AuditLog;
  backups: Backups;
  branch_stock: BranchStock;
  branches: Branches;
  brands: Brands;
  bundle_items: BundleItems;
  bundles: Bundles;
  categories: Categories;
  credit_note_lines: CreditNoteLines;
  credit_notes: CreditNotes;
  customer_credit_cache: CustomerCreditCache;
  customer_credit_ledger: CustomerCreditLedger;
  customer_merge_log: CustomerMergeLog;
  customers: Customers;
  delivery_challan_lines: DeliveryChallanLines;
  delivery_challans: DeliveryChallans;
  document_sequences: DocumentSequences;
  employee_shifts: EmployeeShifts;
  employees: Employees;
  expense_categories: ExpenseCategories;
  expenses: Expenses;
  grn: Grn;
  grn_lines: GrnLines;
  hsn_tax_rates: HsnTaxRates;
  invoice_lines: InvoiceLines;
  invoice_payments: InvoicePayments;
  invoices: Invoices;
  leave_requests: LeaveRequests;
  login_attempts: LoginAttempts;
  loyalty_transactions: LoyaltyTransactions;
  marketing_campaigns: MarketingCampaigns;
  otp_requests: OtpRequests;
  paint_tint_records: PaintTintRecords;
  password_reset_tokens: PasswordResetTokens;
  payroll_entries: PayrollEntries;
  product_barcodes: ProductBarcodes;
  product_prices: ProductPrices;
  product_units: ProductUnits;
  products: Products;
  purchase_order_lines: PurchaseOrderLines;
  purchase_orders: PurchaseOrders;
  quotation_lines: QuotationLines;
  quotations: Quotations;
  registration_requests: RegistrationRequests;
  return_windows: ReturnWindows;
  sales_return_lines: SalesReturnLines;
  sales_returns: SalesReturns;
  shifts: Shifts;
  stock_audit_lines: StockAuditLines;
  stock_audits: StockAudits;
  stock_batches: StockBatches;
  stock_conflicts: StockConflicts;
  stock_ledger: StockLedger;
  stock_serials: StockSerials;
  stock_transfer_lines: StockTransferLines;
  stock_transfers: StockTransfers;
  stock_writeoffs: StockWriteoffs;
  till_events: TillEvents;
  till_sessions: TillSessions;
  training_journals: TrainingJournals;
  user_sessions: UserSessions;
  users: Users;
  vendor_debit_note_lines: VendorDebitNoteLines;
  vendor_debit_notes: VendorDebitNotes;
  vendor_ledger: VendorLedger;
  vendor_product_map: VendorProductMap;
  vendors: Vendors;
  warranties: Warranties;
  warranty_claims: WarrantyClaims;
  whatsapp_message_log: WhatsappMessageLog;
}
