-- ============================================================================
-- Hardware Store ERP — COMPLETE SEED (development / demo)
-- Single authoritative file. Run AFTER db/schema.sql, as the same OWNER role:
--     psql "$DATABASE_URL" -f db/schema.sql
--     psql "$DATABASE_URL" -f db/seed.sql
--
-- Produces: 3 branches, 11 users across all 5 roles, 25 products in 7
-- categories, 5 vendors, 60 customers, every Section-17 admin setting, and ~9
-- months of realistic transactional history (GRNs, ~10k invoices with seasonal
-- Diwali/monsoon shape, till sessions, expenses, attendance, returns + credit
-- notes) so the dashboards have real trends rather than placeholder numbers.
--
-- DEMO CREDENTIALS (development only — rotate before any real deployment):
--   Owner/Admin       owner@hardwareerp.in     / Owner@12345
--   Branch Manager    sunita@hardwareerp.in    / Manager@12345   (Andheri West)
--   Branch Manager    vikas@hardwareerp.in     / Manager@12345   (Thane)
--   Branch Manager    anita@hardwareerp.in     / Manager@12345   (Pune)
--   Accountant        meera@hardwareerp.in     / Account@12345   (Andheri West)
--   Cashier           phone 9900000005         / PIN 1234        (Andheri West)
--   Cashier           phone 9900000006         / PIN 1234        (Thane)
--   Cashier           phone 9900000007         / PIN 1234        (Pune)
--   Inventory staff   phone 9900000008         / PIN 1234        (Andheri West)
-- Every hash below is generated by pgcrypto crypt(..., gen_salt('bf', 12)) at
-- seed time — no plaintext secret is ever stored in a column.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------- Branches --
INSERT INTO branches (branch_id, name, address, state_code, gstin, phone, is_active) VALUES
 ('11111111-1111-1111-1111-111111111111','Andheri West','Shop 4, SV Road, Andheri West, Mumbai','MH','27AAAAA0000A1Z5','9820000001',true),
 ('22222222-2222-2222-2222-222222222222','Thane Station Road','12 Station Road, Thane West','MH','27AAAAA0000A1Z5','9820000002',true),
 ('33333333-3333-3333-3333-333333333333','Pune Kothrud','88 Kothrud Main Road, Pune','MH','27AAAAA0000A1Z5','9820000003',true)
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------------- Users --
-- 7.1 role matrix, one live account per role. Only OWNER_ADMIN is chain-wide;
-- every other account is pinned to exactly one branch, which is what makes
-- requirement 6 ("a member of a branch has access to that branch only") true.
INSERT INTO users (user_id, branch_id, role, full_name, phone, email, password_hash, pin_hash, language_pref) VALUES
 ('a0000000-0000-0000-0000-000000000001', NULL,
   'OWNER_ADMIN','Rohan Mehta','9900000001','owner@hardwareerp.in',
   crypt('Owner@12345', gen_salt('bf', 12)), crypt('4321', gen_salt('bf', 12)),'en'),
 ('a0000000-0000-0000-0000-000000000002','11111111-1111-1111-1111-111111111111',
   'BRANCH_MANAGER','Sunita Rao','9900000002','sunita@hardwareerp.in',
   crypt('Manager@12345', gen_salt('bf', 12)), crypt('1111', gen_salt('bf', 12)),'en'),
 ('a0000000-0000-0000-0000-000000000003','22222222-2222-2222-2222-222222222222',
   'BRANCH_MANAGER','Vikas Patil','9900000003','vikas@hardwareerp.in',
   crypt('Manager@12345', gen_salt('bf', 12)), crypt('2222', gen_salt('bf', 12)),'en'),
 ('a0000000-0000-0000-0000-000000000004','33333333-3333-3333-3333-333333333333',
   'BRANCH_MANAGER','Anita Deshmukh','9900000004','anita@hardwareerp.in',
   crypt('Manager@12345', gen_salt('bf', 12)), crypt('3333', gen_salt('bf', 12)),'en'),
 ('a0000000-0000-0000-0000-000000000005','11111111-1111-1111-1111-111111111111',
   'CASHIER','Ramesh Yadav','9900000005',NULL,
   NULL, crypt('1234', gen_salt('bf', 12)),'hi'),
 ('a0000000-0000-0000-0000-000000000006','22222222-2222-2222-2222-222222222222',
   'CASHIER','Priya Nair','9900000006',NULL,
   NULL, crypt('1234', gen_salt('bf', 12)),'en'),
 ('a0000000-0000-0000-0000-000000000007','33333333-3333-3333-3333-333333333333',
   'CASHIER','Kiran Joshi','9900000007',NULL,
   NULL, crypt('1234', gen_salt('bf', 12)),'en'),
 ('a0000000-0000-0000-0000-000000000008','11111111-1111-1111-1111-111111111111',
   'INVENTORY_STAFF','Deepak Sharma','9900000008',NULL,
   NULL, crypt('1234', gen_salt('bf', 12)),'hi'),
 ('a0000000-0000-0000-0000-000000000009','11111111-1111-1111-1111-111111111111',
   'ACCOUNTANT','Meera Iyer','9900000009','meera@hardwareerp.in',
   crypt('Account@12345', gen_salt('bf', 12)), NULL,'en'),
 ('a0000000-0000-0000-0000-000000000010','22222222-2222-2222-2222-222222222222',
   'INVENTORY_STAFF','Farhan Qureshi','9900000010',NULL,
   NULL, crypt('1234', gen_salt('bf', 12)),'en'),
 ('a0000000-0000-0000-0000-000000000011','33333333-3333-3333-3333-333333333333',
   'CASHIER','Shalini Gokhale','9900000011',NULL,
   NULL, crypt('1234', gen_salt('bf', 12)),'hi')
ON CONFLICT DO NOTHING;

-- ------------------------------------------------- Admin settings (§17) -----
-- Every ⚙ toggle in the requirements' consolidated settings table, at its
-- documented default. branch_id NULL = chain-wide default; a per-branch row
-- overrides it. Values are JSONB so numbers/strings/booleans all round-trip.
INSERT INTO admin_settings (setting_key, branch_id, value, updated_by) VALUES
 -- Catalog & pricing
 ('multi_unit_sale_per_item',        NULL, 'true',                     'a0000000-0000-0000-0000-000000000001'),
 ('enable_tinting_records',          NULL, 'true',                     'a0000000-0000-0000-0000-000000000001'),
 ('enable_bundles',                  NULL, 'false',                    'a0000000-0000-0000-0000-000000000001'),
 ('allow_branch_price_override',     NULL, 'false',                    'a0000000-0000-0000-0000-000000000001'),
 ('branch_manager_cost_visibility',  NULL, 'false',                    'a0000000-0000-0000-0000-000000000001'),
 ('default_item_price_type',         NULL, '"TAX_INCLUSIVE"',          'a0000000-0000-0000-0000-000000000001'),
 ('fractional_unit_rounding_dp',     NULL, '2',                        'a0000000-0000-0000-0000-000000000001'),
 -- Billing / POS
 ('staff_discount_limit_pct',        NULL, '5',                        'a0000000-0000-0000-0000-000000000001'),
 ('allow_negative_stock',            NULL, 'false',                    'a0000000-0000-0000-0000-000000000001'),
 ('require_barcode_at_billing',      NULL, 'false',                    'a0000000-0000-0000-0000-000000000001'),
 ('offline_sync_conflict_rule',      NULL, '"FIRST_TO_CLOUD_WINS"',    'a0000000-0000-0000-0000-000000000001'),
 -- Inventory
 ('enable_batch_tracking',           NULL, 'true',                     'a0000000-0000-0000-0000-000000000001'),
 ('valuation_method',                NULL, '"WEIGHTED_AVERAGE"',       'a0000000-0000-0000-0000-000000000001'),
 -- Quotations
 ('enable_quotations_module',        NULL, 'true',                     'a0000000-0000-0000-0000-000000000001'),
 ('quotation_stock_reservation',     NULL, 'false',                    'a0000000-0000-0000-0000-000000000001'),
 ('quotation_hold_days',             NULL, '3',                        'a0000000-0000-0000-0000-000000000001'),
 -- Credit
 ('allow_offline_credit_sales',      NULL, '"CAP_50_PCT"',             'a0000000-0000-0000-0000-000000000001'),
 -- Auth & security (7.2 / 7.4)
 ('login_method_by_role',            NULL, '{"OWNER_ADMIN":"GOOGLE","BRANCH_MANAGER":"GOOGLE","CASHIER":"PHONE_PIN","INVENTORY_STAFF":"PHONE_PIN","ACCOUNTANT":"GOOGLE"}', 'a0000000-0000-0000-0000-000000000001'),
 ('otp_expiry_minutes',              NULL, '5',                        'a0000000-0000-0000-0000-000000000001'),
 ('pin_max_attempts',                NULL, '3',                        'a0000000-0000-0000-0000-000000000001'),
 ('lockout_minutes',                 NULL, '15',                       'a0000000-0000-0000-0000-000000000001'),
 ('session_timeout_minutes',         NULL, '720',                      'a0000000-0000-0000-0000-000000000001'),
 -- Loyalty & CRM
 ('allow_loyalty_discount_stacking', NULL, 'false',                    'a0000000-0000-0000-0000-000000000001'),
 ('loyalty_earn_points_per_100',     NULL, '1',                        'a0000000-0000-0000-0000-000000000001'),
 ('loyalty_point_value_rupees',      NULL, '1',                        'a0000000-0000-0000-0000-000000000001'),
 ('loyalty_point_expiry_days',       NULL, '365',                      'a0000000-0000-0000-0000-000000000001'),
 ('enable_birthday_greetings',       NULL, 'true',                     'a0000000-0000-0000-0000-000000000001'),
 -- Returns & warranty
 ('refund_method',                   NULL, '"ADMIN_CHOICE"',           'a0000000-0000-0000-0000-000000000001'),
 ('return_window_days',              NULL, '7',                        'a0000000-0000-0000-0000-000000000001'),
 -- Expenses & HR
 ('expense_approval_threshold',      NULL, '5000',                     'a0000000-0000-0000-0000-000000000001'),
 ('attendance_method',               NULL, '"APP_CHECKIN"',            'a0000000-0000-0000-0000-000000000001'),
 ('enable_payroll_module',           NULL, 'false',                    'a0000000-0000-0000-0000-000000000001'),
 -- Compliance
 ('backup_frequency_hours',          NULL, '24',                       'a0000000-0000-0000-0000-000000000001'),
 ('einvoice_enabled',                NULL, 'false',                    'a0000000-0000-0000-0000-000000000001')
ON CONFLICT DO NOTHING;

-- A worked example of a per-branch override: Pune runs a tighter discount limit.
INSERT INTO admin_settings (setting_key, branch_id, value, updated_by) VALUES
 ('staff_discount_limit_pct','33333333-3333-3333-3333-333333333333','3','a0000000-0000-0000-0000-000000000001')
ON CONFLICT DO NOTHING;

-- -------------------------------------------------------------- Categories --
INSERT INTO categories (category_id, name) VALUES
 ('c0000000-0000-0000-0000-000000000001','Plumbing'),
 ('c0000000-0000-0000-0000-000000000002','Paint'),
 ('c0000000-0000-0000-0000-000000000003','Electrical'),
 ('c0000000-0000-0000-0000-000000000004','Hand Tools'),
 ('c0000000-0000-0000-0000-000000000005','Power Tools'),
 ('c0000000-0000-0000-0000-000000000006','Hardware & Fasteners'),
 ('c0000000-0000-0000-0000-000000000007','Sanitaryware')
ON CONFLICT DO NOTHING;

INSERT INTO brands (brand_id, name) VALUES
 ('b0000000-0000-0000-0000-000000000001','Supreme'),
 ('b0000000-0000-0000-0000-000000000002','Asian Paints'),
 ('b0000000-0000-0000-0000-000000000003','Havells'),
 ('b0000000-0000-0000-0000-000000000004','Bosch'),
 ('b0000000-0000-0000-0000-000000000005','Stanley'),
 ('b0000000-0000-0000-0000-000000000006','Jaquar'),
 ('b0000000-0000-0000-0000-000000000007','Generic')
ON CONFLICT DO NOTHING;

-- 2.7: rates are effective-dated, never overwritten. The 7318 row below models a
-- real mid-life rate change so historical invoices demonstrably keep their own rate.
INSERT INTO hsn_tax_rates (hsn_code, gst_rate_pct, effective_from, effective_to) VALUES
 ('3917', 18, '2024-01-01', NULL),
 ('3208', 18, '2024-01-01', NULL),
 ('8536', 18, '2024-01-01', NULL),
 ('8203', 18, '2024-01-01', NULL),
 ('8467', 18, '2024-01-01', NULL),
 ('6910', 18, '2024-01-01', NULL),
 ('8301', 18, '2024-01-01', NULL),
 ('7318', 18, '2024-01-01', '2025-04-01'),
 ('7318', 12, '2025-04-01', NULL)
ON CONFLICT DO NOTHING;
-- ---------- Products (25 across categories) ----------
INSERT INTO products (product_id, sku, name, category_id, brand_id, base_unit, hsn_code, default_price_type, reference_purchase_price, batch_tracked, serial_tracked) VALUES
 ('10000000-0000-0000-0000-000000000001','PLB-PIPE-15','Supreme CPVC Pipe 15mm (per metre)','c0000000-0000-0000-0000-000000000001','b0000000-0000-0000-0000-000000000001','METRE','3917','TAX_INCLUSIVE',42,false,false),
 ('10000000-0000-0000-0000-000000000002','PLB-PIPE-25','Supreme CPVC Pipe 25mm (per metre)','c0000000-0000-0000-0000-000000000001','b0000000-0000-0000-0000-000000000001','METRE','3917','TAX_INCLUSIVE',68,false,false),
 ('10000000-0000-0000-0000-000000000003','PLB-ELBOW-15','CPVC Elbow 15mm','c0000000-0000-0000-0000-000000000001','b0000000-0000-0000-0000-000000000001','PIECE','3917','TAX_INCLUSIVE',12,false,false),
 ('10000000-0000-0000-0000-000000000004','PLB-TAP-STD','Jaquar Basin Tap Standard','c0000000-0000-0000-0000-000000000007','b0000000-0000-0000-0000-000000000006','PIECE','6910','TAX_INCLUSIVE',650,false,false),
 ('10000000-0000-0000-0000-000000000005','PLB-WC-SEAT','Jaquar WC Seat Cover','c0000000-0000-0000-0000-000000000007','b0000000-0000-0000-0000-000000000006','PIECE','6910','TAX_INCLUSIVE',900,false,false),
 ('10000000-0000-0000-0000-000000000006','PNT-EMU-1L','Asian Paints Emulsion 1L White','c0000000-0000-0000-0000-000000000002','b0000000-0000-0000-0000-000000000002','LITRE','3208','TAX_INCLUSIVE',220,true,false),
 ('10000000-0000-0000-0000-000000000007','PNT-EMU-4L','Asian Paints Emulsion 4L White','c0000000-0000-0000-0000-000000000002','b0000000-0000-0000-0000-000000000002','LITRE','3208','TAX_INCLUSIVE',210,true,false),
 ('10000000-0000-0000-0000-000000000008','PNT-ENAMEL-1L','Asian Paints Enamel 1L Blue','c0000000-0000-0000-0000-000000000002','b0000000-0000-0000-0000-000000000002','LITRE','3208','TAX_INCLUSIVE',260,true,false),
 ('10000000-0000-0000-0000-000000000009','PNT-PRIMER-1L','Asian Paints Wall Primer 1L','c0000000-0000-0000-0000-000000000002','b0000000-0000-0000-0000-000000000002','LITRE','3208','TAX_INCLUSIVE',180,true,false),
 ('10000000-0000-0000-0000-000000000010','ELC-WIRE-1.5','Havells 1.5sqmm Wire (per metre)','c0000000-0000-0000-0000-000000000003','b0000000-0000-0000-0000-000000000003','METRE','8536','TAX_INCLUSIVE',9,false,false),
 ('10000000-0000-0000-0000-000000000011','ELC-WIRE-2.5','Havells 2.5sqmm Wire (per metre)','c0000000-0000-0000-0000-000000000003','b0000000-0000-0000-0000-000000000003','METRE','8536','TAX_INCLUSIVE',14,false,false),
 ('10000000-0000-0000-0000-000000000012','ELC-SWITCH-6A','Havells Modular Switch 6A','c0000000-0000-0000-0000-000000000003','b0000000-0000-0000-0000-000000000003','PIECE','8536','TAX_INCLUSIVE',35,false,false),
 ('10000000-0000-0000-0000-000000000013','ELC-MCB-32A','Havells MCB 32A','c0000000-0000-0000-0000-000000000003','b0000000-0000-0000-0000-000000000003','PIECE','8536','TAX_INCLUSIVE',180,false,false),
 ('10000000-0000-0000-0000-000000000014','ELC-LED-9W','Havells LED Bulb 9W','c0000000-0000-0000-0000-000000000003','b0000000-0000-0000-0000-000000000003','PIECE','8536','TAX_INCLUSIVE',60,false,false),
 ('10000000-0000-0000-0000-000000000015','HT-HAMMER-STD','Stanley Claw Hammer','c0000000-0000-0000-0000-000000000004','b0000000-0000-0000-0000-000000000005','PIECE','8203','TAX_INCLUSIVE',280,false,false),
 ('10000000-0000-0000-0000-000000000016','HT-SCREWDRIVER-SET','Stanley Screwdriver Set 6pc','c0000000-0000-0000-0000-000000000004','b0000000-0000-0000-0000-000000000005','PIECE','8203','TAX_INCLUSIVE',350,false,false),
 ('10000000-0000-0000-0000-000000000017','HT-WRENCH-ADJ','Stanley Adjustable Wrench 10 inch','c0000000-0000-0000-0000-000000000004','b0000000-0000-0000-0000-000000000005','PIECE','8203','TAX_INCLUSIVE',320,false,false),
 ('10000000-0000-0000-0000-000000000018','PT-DRILL-13MM','Bosch Impact Drill 13mm','c0000000-0000-0000-0000-000000000005','b0000000-0000-0000-0000-000000000004','PIECE','8467','TAX_INCLUSIVE',3200,false,true),
 ('10000000-0000-0000-0000-000000000019','PT-GRINDER-4IN','Bosch Angle Grinder 4 inch','c0000000-0000-0000-0000-000000000005','b0000000-0000-0000-0000-000000000004','PIECE','8467','TAX_INCLUSIVE',2600,false,true),
 ('10000000-0000-0000-0000-000000000020','PT-JIGSAW','Bosch Jigsaw','c0000000-0000-0000-0000-000000000005','b0000000-0000-0000-0000-000000000004','PIECE','8467','TAX_INCLUSIVE',4100,false,true),
 ('10000000-0000-0000-0000-000000000021','HW-SCREW-BOX','Wood Screw 1 inch (box of 100)','c0000000-0000-0000-0000-000000000006','b0000000-0000-0000-0000-000000000007','PIECE','7318','TAX_INCLUSIVE',1,false,false),
 ('10000000-0000-0000-0000-000000000022','HW-BOLT-M8','Bolt M8x50 Galvanised','c0000000-0000-0000-0000-000000000006','b0000000-0000-0000-0000-000000000007','PIECE','7318','TAX_INCLUSIVE',3,false,false),
 ('10000000-0000-0000-0000-000000000023','HW-HINGE-4IN','Door Hinge 4 inch SS','c0000000-0000-0000-0000-000000000006','b0000000-0000-0000-0000-000000000007','PIECE','7318','TAX_INCLUSIVE',35,false,false),
 ('10000000-0000-0000-0000-000000000024','HW-PADLOCK-50','Padlock 50mm Brass','c0000000-0000-0000-0000-000000000006','b0000000-0000-0000-0000-000000000007','PIECE','8301','TAX_INCLUSIVE',150,false,false),
 ('10000000-0000-0000-0000-000000000025','SAN-FLUSH-TANK','Jaquar Flush Tank 10L','c0000000-0000-0000-0000-000000000007','b0000000-0000-0000-0000-000000000006','PIECE','6910','TAX_INCLUSIVE',1450,false,false)
ON CONFLICT DO NOTHING;


-- default sale units (PIECE/METRE/LITRE = base unit itself, multiplier 1)
INSERT INTO product_units (product_id, unit_label, multiplier_to_base, is_default_sale_unit)
SELECT product_id, base_unit::text, 1, true FROM products
ON CONFLICT DO NOTHING;
-- box unit for the screw product
INSERT INTO product_units (product_id, unit_label, multiplier_to_base, is_default_sale_unit)
VALUES ('10000000-0000-0000-0000-000000000021','BOX_100',100,false) ON CONFLICT DO NOTHING;

-- Selling prices (mrp ~15-25% over ref purchase price)
INSERT INTO product_prices (product_id, mrp, selling_price, effective_from)
SELECT product_id,
       ROUND(reference_purchase_price * 1.45, 2),
       ROUND(reference_purchase_price * 1.30, 2),
       '2025-01-01'::timestamptz
FROM products
ON CONFLICT DO NOTHING;

-- ---------- Vendors ----------
INSERT INTO vendors (vendor_id, name, gstin, phone, payment_terms_days, is_active) VALUES
 ('d0000000-0000-0000-0000-000000000001','Supreme Distributors Pvt Ltd','27BBBBB0001B1Z1','9811111111',30,true),
 ('d0000000-0000-0000-0000-000000000002','Asian Paints Regional Depot','27BBBBB0002B1Z1','9811111112',15,true),
 ('d0000000-0000-0000-0000-000000000003','Havells Authorised Distributor','27BBBBB0003B1Z1','9811111113',30,true),
 ('d0000000-0000-0000-0000-000000000004','Bosch Power Tools Wholesale','27BBBBB0004B1Z1','9811111114',45,true),
 ('d0000000-0000-0000-0000-000000000005','Local Hardware Supplies Co','27BBBBB0005B1Z1','9811111115',7,true)
ON CONFLICT DO NOTHING;

-- ---------- Expense categories ----------
INSERT INTO expense_categories (category_id, name) VALUES
 ('e0000000-0000-0000-0000-000000000001','Rent'),
 ('e0000000-0000-0000-0000-000000000002','Salaries'),
 ('e0000000-0000-0000-0000-000000000003','Electricity'),
 ('e0000000-0000-0000-0000-000000000004','Maintenance'),
 ('e0000000-0000-0000-0000-000000000005','Marketing'),
 ('e0000000-0000-0000-0000-000000000006','Miscellaneous')
ON CONFLICT DO NOTHING;

-- ---------- Customers (60) ----------
INSERT INTO customers (customer_id, phone, name, email, dob, customer_type, credit_allowed, credit_limit, loyalty_points_balance, created_at)
SELECT
  ('f0000000-0000-0000-0000-' || lpad(i::text, 12, '0'))::uuid,
  '98' || lpad((10000000 + i)::text, 8, '0'),
  (ARRAY['Ravi','Suresh','Amit','Sanjay','Pooja','Neha','Kavita','Manoj','Arjun','Divya','Rahul','Sneha','Vijay','Anil','Meena'])[1 + (i % 15)] || ' ' ||
  (ARRAY['Kumar','Sharma','Patel','Reddy','Singh','Gupta','Joshi','Nair','Rao','Verma'])[1 + (i % 10)],
  NULL, (DATE '1975-01-01' + (i * 137 || ' days')::interval)::date,
  CASE WHEN i % 10 = 0 THEN 'B2B_CONTRACTOR' ELSE 'RETAIL' END::customer_type,
  CASE WHEN i % 8 = 0 THEN true ELSE false END,
  CASE WHEN i % 8 = 0 THEN 25000 ELSE 0 END,
  (i * 13) % 500,
  now() - ((270 - i) || ' days')::interval
FROM generate_series(1, 60) AS i
ON CONFLICT DO NOTHING;


-- 2.2 multi-unit sale: a higher sale unit is ONLY ever a multiple of base_unit,
-- never an independently typed price (2.2.1). Box/reel/tin rows below prove the
-- billing engine's conversion path, not just the schema's ability to store it.
INSERT INTO product_units (product_id, unit_label, multiplier_to_base, is_default_sale_unit)
VALUES
 ('10000000-0000-0000-0000-000000000021','BOX_100',100,false),   -- 1 box = 100 screws
 ('10000000-0000-0000-0000-000000000022','BOX_50',50,false),     -- 1 box = 50 bolts
 ('10000000-0000-0000-0000-000000000010','REEL_90',90,false),    -- 1 reel = 90 m of 1.5sqmm wire
 ('10000000-0000-0000-0000-000000000011','REEL_90',90,false),
 ('10000000-0000-0000-0000-000000000001','LENGTH_3M',3,false),   -- pipe sold as a 3 m length or cut-to-length
 ('10000000-0000-0000-0000-000000000002','LENGTH_3M',3,false),
 ('10000000-0000-0000-0000-000000000007','TIN_4L',4,false),      -- 4 L tin of a LITRE-based paint
 ('10000000-0000-0000-0000-000000000023','BOX_20',20,false)
ON CONFLICT DO NOTHING;

-- 3.9 barcodes exist where the manufacturer prints one; fuzzy search remains the
-- default lookup path, so most items deliberately have none.
INSERT INTO product_barcodes (product_id, barcode, is_internally_generated) VALUES
 ('10000000-0000-0000-0000-000000000014','8901234500014',false),
 ('10000000-0000-0000-0000-000000000012','8901234500012',false),
 ('10000000-0000-0000-0000-000000000018','8901234500018',false),
 ('10000000-0000-0000-0000-000000000019','8901234500019',false),
 ('10000000-0000-0000-0000-000000000020','8901234500020',false),
 ('10000000-0000-0000-0000-000000000006','8901234500006',false),
 ('10000000-0000-0000-0000-000000000024','ERP-INT-000024',true)
ON CONFLICT DO NOTHING;

-- 12.2 warranty terms, by category for the general case and by product where the
-- manufacturer's term differs.
INSERT INTO warranties (category_id, product_id, duration_months) VALUES
 ('c0000000-0000-0000-0000-000000000005', NULL, 12),   -- Power Tools
 ('c0000000-0000-0000-0000-000000000003', NULL, 6),    -- Electrical
 (NULL, '10000000-0000-0000-0000-000000000018', 24),   -- Bosch drill: 2 years
 (NULL, '10000000-0000-0000-0000-000000000025', 60)    -- Flush tank: 5 years
ON CONFLICT DO NOTHING;

-- 12.3 return window: 7 days chain-wide by default, longer for electricals/power
-- tools which route to a warranty claim once outside it.
INSERT INTO return_windows (category_id, window_days) VALUES
 ('c0000000-0000-0000-0000-000000000003', 15),
 ('c0000000-0000-0000-0000-000000000005', 15),
 ('c0000000-0000-0000-0000-000000000002', 3)   -- Paint: tinted to order, short window
ON CONFLICT DO NOTHING;

-- 4.9 vendor-item mapping, several vendors per item with one preferred.
INSERT INTO vendor_product_map (vendor_id, product_id, vendor_sku, last_purchase_rate, is_preferred)
SELECT v.vendor_id, p.product_id, 'V-' || p.sku, p.reference_purchase_price,
       (v.vendor_id = CASE
            WHEN p.brand_id = 'b0000000-0000-0000-0000-000000000001' THEN 'd0000000-0000-0000-0000-000000000001'
            WHEN p.brand_id = 'b0000000-0000-0000-0000-000000000002' THEN 'd0000000-0000-0000-0000-000000000002'
            WHEN p.brand_id = 'b0000000-0000-0000-0000-000000000003' THEN 'd0000000-0000-0000-0000-000000000003'
            WHEN p.brand_id = 'b0000000-0000-0000-0000-000000000004' THEN 'd0000000-0000-0000-0000-000000000004'
            ELSE 'd0000000-0000-0000-0000-000000000005' END::uuid)
FROM products p CROSS JOIN vendors v
WHERE v.vendor_id IN ('d0000000-0000-0000-0000-000000000005'::uuid, CASE
        WHEN p.brand_id = 'b0000000-0000-0000-0000-000000000001' THEN 'd0000000-0000-0000-0000-000000000001'
        WHEN p.brand_id = 'b0000000-0000-0000-0000-000000000002' THEN 'd0000000-0000-0000-0000-000000000002'
        WHEN p.brand_id = 'b0000000-0000-0000-0000-000000000003' THEN 'd0000000-0000-0000-0000-000000000003'
        WHEN p.brand_id = 'b0000000-0000-0000-0000-000000000004' THEN 'd0000000-0000-0000-0000-000000000004'
        ELSE 'd0000000-0000-0000-0000-000000000005' END::uuid)
ON CONFLICT DO NOTHING;

-- --------------------------------------------------------------- Employees --
INSERT INTO employees (employee_id, user_id, branch_id, designation, joined_at)
SELECT gen_random_uuid(), user_id, branch_id, role::text, '2024-06-01'
FROM users WHERE branch_id IS NOT NULL
ON CONFLICT DO NOTHING;

-- 10.4 shift definitions per branch.
INSERT INTO shifts (branch_id, name, start_time, end_time)
SELECT branch_id, s.name, s.st, s.en
FROM branches CROSS JOIN (VALUES
    ('Morning','09:30'::time,'15:00'::time),
    ('Evening','15:00'::time,'21:30'::time),
    ('Full Day','09:30'::time,'21:30'::time)
) AS s(name, st, en)
ON CONFLICT DO NOTHING;

-- 11.1 marketing campaigns, Hindi and English (requirement #1 applies to
-- customer-facing messages too, not only to the UI chrome).
INSERT INTO marketing_campaigns (name, campaign_type, message_template, scheduled_at, created_by) VALUES
 ('Birthday Greeting (EN)','BIRTHDAY','Happy birthday {{name}}! Enjoy 10% off at any of our branches this week.', NULL, 'a0000000-0000-0000-0000-000000000001'),
 ('Birthday Greeting (HI)','BIRTHDAY','जन्मदिन मुबारक {{name}}! इस हफ्ते हमारी किसी भी शाखा पर 10% की छूट।', NULL, 'a0000000-0000-0000-0000-000000000001'),
 ('Diwali Offer 2026','FESTIVAL','Diwali dhamaka! Flat 15% off on all power tools until {{date}}.', now() + interval '30 days', 'a0000000-0000-0000-0000-000000000001'),
 ('Winback — no purchase in 90 days','WINBACK','We have missed you {{name}}. Here is 5% off your next visit.', NULL, 'a0000000-0000-0000-0000-000000000001')
ON CONFLICT DO NOTHING;

-- 16 training journals, versioned and bilingual.
INSERT INTO training_journals (journal_type, language, version, content_url) VALUES
 ('ADMIN','en',1,'/docs/admin-journal-en-v1.md'),
 ('ADMIN','hi',1,'/docs/admin-journal-hi-v1.md'),
 ('STAFF','en',1,'/docs/staff-journal-en-v1.md'),
 ('STAFF','hi',1,'/docs/staff-journal-hi-v1.md')
ON CONFLICT DO NOTHING;

-- 15 backup history with a documented restore test.
INSERT INTO backups (taken_at, storage_ref, status, restore_tested_at)
SELECT now() - (i || ' days')::interval, 's3://erp-backups/daily/' || to_char(now() - (i || ' days')::interval,'YYYY-MM-DD') || '.dump',
       'COMPLETED', CASE WHEN i % 30 = 0 THEN now() - (i || ' days')::interval + interval '2 hours' ELSE NULL END
FROM generate_series(0, 29) i;

COMMIT;

-- ============================================================================
-- TRANSACTIONAL HISTORY — GRNs, invoices, till sessions, loyalty, WhatsApp queue
-- ============================================================================

DO $$
DECLARE
  branch_ids UUID[] := ARRAY['11111111-1111-1111-1111-111111111111','22222222-2222-2222-2222-222222222222','33333333-3333-3333-3333-333333333333'];
  cashier_by_branch JSONB := '{
    "11111111-1111-1111-1111-111111111111":"a0000000-0000-0000-0000-000000000005",
    "22222222-2222-2222-2222-222222222222":"a0000000-0000-0000-0000-000000000006",
    "33333333-3333-3333-3333-333333333333":"a0000000-0000-0000-0000-000000000007"
  }';
  vendor_ids UUID[];
  product_ids UUID[];
  b UUID;
  d DATE;
  day_count INT;
  grn_id UUID; grn_no TEXT; grn_seq INT := 1000;
  po_id UUID;
  vend UUID;
  prod RECORD;
  rate NUMERIC;
  qty NUMERIC;
  cur_qty NUMERIC; cur_cost NUMERIC;
  new_cost NUMERIC;
  invoices_per_day INT;
  inv INT;
  v_invoice_id UUID;
  inv_seq INT;
  branch_code TEXT;
  v_fy TEXT;
  v_points INT;
  cust UUID;
  n_lines INT;
  li INT;
  p RECORD;
  sale_price NUMERIC;
  gst_rate NUMERIC;
  qty_sold NUMERIC;
  taxable NUMERIC; cgst NUMERIC; sgst NUMERIC;
  v_subtotal NUMERIC; cgst_t NUMERIC; sgst_t NUMERIC; v_grand NUMERIC;
  cashier UUID;
  ts TIMESTAMPTZ;
  pay_method TEXT;
  v_line_id UUID;
  till_id UUID;
  branch_mult NUMERIC;
  seasonal NUMERIC;
  weekday_mult NUMERIC;
  w INT;
  this_grn_id UUID;
  grn_total NUMERIC;
BEGIN
  SELECT array_agg(vendor_id) INTO vendor_ids FROM vendors;
  SELECT array_agg(product_id) INTO product_ids FROM products;

  -- ============== GRNs: weekly restock per branch for 40 weeks back ==============
  FOR b IN SELECT unnest(branch_ids) LOOP
    branch_mult := CASE b WHEN branch_ids[1] THEN 1.3 WHEN branch_ids[2] THEN 1.0 ELSE 0.8 END;
    FOR w IN 0..39 LOOP
      d := CURRENT_DATE - (w * 7);
      vend := vendor_ids[1 + (w % array_length(vendor_ids,1))];
      grn_seq := grn_seq + 1;
      grn_no := 'GRN-' || to_char(d,'YYYYMM') || '-' || grn_seq;
      this_grn_id := gen_random_uuid();
      INSERT INTO grn (grn_id, branch_id, vendor_id, grn_number, received_at, created_by)
      VALUES (this_grn_id, b, vend, grn_no, d::timestamptz + interval '9 hours', 'a0000000-0000-0000-0000-000000000008');

      FOR prod IN SELECT product_id, reference_purchase_price, base_unit FROM products ORDER BY random() LIMIT 8 LOOP
        qty := (20 + (random()*80))::numeric(14,4) * branch_mult;
        rate := prod.reference_purchase_price * (0.95 + random()*0.1);

        SELECT base_unit_qty, weighted_avg_cost INTO cur_qty, cur_cost
        FROM branch_stock WHERE branch_id = b AND product_id = prod.product_id;
        IF NOT FOUND THEN
          cur_qty := 0; cur_cost := rate;
          INSERT INTO branch_stock (branch_id, product_id, base_unit_qty, weighted_avg_cost, reorder_min, reorder_max)
          VALUES (b, prod.product_id, 0, rate, 10, 200);
        END IF;

        new_cost := CASE WHEN (cur_qty + qty) = 0 THEN rate ELSE ((cur_qty*cur_cost)+(qty*rate))/(cur_qty+qty) END;

        INSERT INTO grn_lines (grn_id, product_id, qty_base_unit, rate) VALUES (this_grn_id, prod.product_id, qty, rate);

        UPDATE branch_stock SET base_unit_qty = base_unit_qty + qty, weighted_avg_cost = new_cost, updated_at = now()
        WHERE branch_id = b AND product_id = prod.product_id;

        INSERT INTO stock_ledger (branch_id, product_id, movement_type, base_unit_qty_change, cost_at_movement, ref_table, ref_id, created_by, created_at)
        VALUES (b, prod.product_id, 'PURCHASE', qty, rate, 'grn', this_grn_id, 'a0000000-0000-0000-0000-000000000008', d::timestamptz + interval '9 hours');
      END LOOP;

      SELECT SUM(gl.qty_base_unit*gl.rate) INTO grn_total FROM grn_lines gl WHERE gl.grn_id = this_grn_id;
      INSERT INTO vendor_ledger (vendor_id, branch_id, entry_type, amount, ref_table, ref_id, balance_after, created_at)
      VALUES (vend, b, 'GRN_PAYABLE', grn_total, 'grn', this_grn_id, grn_total, d::timestamptz + interval '9 hours');
    END LOOP;
  END LOOP;

  -- ============== Invoices: daily sales for the last 270 days per branch ==============
  FOR b IN SELECT unnest(branch_ids) LOOP
    cashier := (cashier_by_branch->>(b::text))::uuid;
    branch_code := upper(substr(replace((SELECT name FROM branches WHERE branch_id = b), ' ', ''), 1, 3));
    inv_seq := 0;
    branch_mult := CASE b WHEN branch_ids[1] THEN 1.4 WHEN branch_ids[2] THEN 1.0 ELSE 0.75 END;

    FOR day_count IN 0..269 LOOP
      d := CURRENT_DATE - day_count;
      -- seasonal bump around Diwali (Oct/Nov) and a dip in monsoon (Jul/Aug)
      seasonal := CASE WHEN EXTRACT(MONTH FROM d) IN (10,11) THEN 1.5
                        WHEN EXTRACT(MONTH FROM d) IN (7,8) THEN 0.8
                        WHEN EXTRACT(MONTH FROM d) IN (12,1) THEN 1.15
                        ELSE 1.0 END;
      weekday_mult := CASE WHEN EXTRACT(DOW FROM d) IN (0,6) THEN 1.3 ELSE 1.0 END;
      invoices_per_day := GREATEST(1, ROUND((6 + random()*10) * branch_mult * seasonal * weekday_mult)::int);

      -- one till session per branch per day
      till_id := gen_random_uuid();
      INSERT INTO till_sessions (session_id, branch_id, counter_id, cashier_user_id, opening_float, opened_at, closed_at, closing_counted_cash, status)
      VALUES (till_id, b, 'COUNTER-1', cashier, 2000, d::timestamptz + interval '9 hours', d::timestamptz + interval '21 hours', 2000 + (500 + random()*4000), 'CLOSED');

      FOR inv IN 1..invoices_per_day LOOP
        ts := d::timestamptz + (make_interval(hours => 9) + (random()*11) * interval '1 hour');
        SELECT customer_id INTO cust FROM customers ORDER BY random() LIMIT 1;
        n_lines := 1 + (random()*3)::int;
        v_subtotal := 0; cgst_t := 0; sgst_t := 0;
        v_invoice_id := gen_random_uuid();
        inv_seq := inv_seq + 1;
        v_fy := erp_fiscal_year(ts);

        INSERT INTO invoices (invoice_id, invoice_number, branch_id, till_session_id, customer_id, invoice_type, status,
                               subtotal, discount_total, cgst_total, sgst_total, igst_total, grand_total,
                               device_created_at, server_received_at, created_by, sold_by_employee_id)
        VALUES (v_invoice_id, 'INV-' || branch_code || '/' || v_fy || '/' || lpad(inv_seq::text, 5, '0'), b, till_id,
                CASE WHEN random() < 0.15 THEN NULL ELSE cust END,
                CASE WHEN random() < 0.7 THEN 'GST' ELSE 'NON_GST' END::invoice_type, 'FINAL'::invoice_status,
                0, 0, 0, 0, 0, 0, ts, ts, cashier,
                (SELECT employee_id FROM employees WHERE user_id = cashier));

        FOR li IN 1..n_lines LOOP
          SELECT pr.product_id, pr.base_unit, pp.selling_price, htr.gst_rate_pct
            INTO p
            FROM products pr
            JOIN product_prices pp ON pp.product_id = pr.product_id AND pp.effective_to IS NULL
            JOIN hsn_tax_rates htr ON htr.hsn_code = pr.hsn_code AND htr.effective_to IS NULL
            ORDER BY random() LIMIT 1;

          qty_sold := CASE WHEN p.base_unit = 'PIECE' THEN (1 + (random()*4))::int
                            ELSE round((1 + random()*8)::numeric, 2) END;
          sale_price := p.selling_price;
          gst_rate := p.gst_rate_pct;
          taxable := round((qty_sold * sale_price) / (1 + gst_rate/100), 2);
          cgst := round(taxable * (gst_rate/2) / 100, 2);
          sgst := cgst;

          v_line_id := gen_random_uuid();
          INSERT INTO invoice_lines (line_id, invoice_id, product_id, qty_in_sale_unit, base_unit_qty, price_type,
                                      rate_locked_at_scan, taxable_value, cgst_amount, sgst_amount, igst_amount)
          VALUES (v_line_id, v_invoice_id, p.product_id, qty_sold, qty_sold, 'TAX_INCLUSIVE', sale_price, taxable, cgst, sgst, 0);

          v_subtotal := v_subtotal + taxable;
          cgst_t := cgst_t + cgst;
          sgst_t := sgst_t + sgst;

          -- decrement stock (allow going slightly negative is blocked by trigger, so clamp)
          UPDATE branch_stock SET base_unit_qty = GREATEST(base_unit_qty - qty_sold, 0.5), updated_at = now()
          WHERE branch_id = b AND product_id = p.product_id;

          INSERT INTO stock_ledger (branch_id, product_id, movement_type, base_unit_qty_change, ref_table, ref_id, created_by, created_at)
          VALUES (b, p.product_id, 'SALE', -qty_sold, 'invoices', v_invoice_id, cashier, ts);
        END LOOP;

        v_grand := v_subtotal + cgst_t + sgst_t;
        UPDATE invoices SET subtotal = v_subtotal, cgst_total = cgst_t, sgst_total = sgst_t, grand_total = v_grand WHERE invoice_id = v_invoice_id;

        pay_method := CASE WHEN random() < 0.35 THEN 'CASH' WHEN random() < 0.7 THEN 'UPI' WHEN random() < 0.9 THEN 'CARD' ELSE 'CREDIT' END;
        INSERT INTO invoice_payments (invoice_id, method, amount) VALUES (v_invoice_id, pay_method::payment_method, v_grand);

        IF pay_method = 'CASH' THEN
          INSERT INTO till_events (session_id, event_type, amount, created_at) VALUES (till_id, 'CASH_SALE', v_grand, ts);
        END IF;

        -- 11.2 loyalty: 1 point per Rs.100 spent, only for identified customers.
        IF cust IS NOT NULL AND random() < 0.6 THEN
          v_points := floor(v_grand / 100)::int;
          IF v_points > 0 THEN
            UPDATE customers SET loyalty_points_balance = loyalty_points_balance + v_points WHERE customer_id = cust;
            INSERT INTO loyalty_transactions (customer_id, invoice_id, txn_type, points, balance_after, created_at)
            VALUES (cust, v_invoice_id, 'EARN', v_points,
                    (SELECT loyalty_points_balance FROM customers WHERE customer_id = cust), ts);
          END IF;
        END IF;

        -- Requirement #4: every invoice for an identified customer is queued for
        -- WhatsApp delivery; the worker drains the queue and retries on failure.
        IF cust IS NOT NULL AND random() < 0.75 THEN
          INSERT INTO whatsapp_message_log (customer_id, invoice_id, to_phone, message_type, body, status, sent_at, queued_at)
          VALUES (cust, v_invoice_id, (SELECT phone FROM customers WHERE customer_id = cust), 'INVOICE_PDF',
                  'Your invoice is attached. Thank you for shopping with us.',
                  CASE WHEN random() < 0.95 THEN 'SENT' ELSE 'FAILED' END,
                  ts + interval '2 minutes', ts);
        END IF;

        IF pay_method = 'CREDIT' AND cust IS NOT NULL THEN
          INSERT INTO customer_credit_ledger (customer_id, branch_id, entry_type, amount, balance_after, ref_table, ref_id, created_at)
          VALUES (cust, b, 'SALE_ON_CREDIT', v_grand,
                  v_grand + COALESCE((SELECT balance_after FROM customer_credit_ledger WHERE customer_id = cust ORDER BY created_at DESC LIMIT 1), 0),
                  'invoices', v_invoice_id, ts);
        END IF;
      END LOOP;

      -- occasional cash drop
      IF random() < 0.3 THEN
        INSERT INTO till_events (session_id, event_type, amount, acknowledged_by, created_at)
        VALUES (till_id, 'CASH_DROP', 1000 + random()*2000, cashier, d::timestamptz + interval '18 hours');
      END IF;
    END LOOP;
  END LOOP;

  RAISE NOTICE 'Transaction seed complete.';
END $$;

-- ============================================================================
-- EXPENSES, HR, RETURNS & CREDIT NOTES
-- ============================================================================

DO $$
DECLARE
  branch_ids UUID[] := ARRAY['11111111-1111-1111-1111-111111111111','22222222-2222-2222-2222-222222222222','33333333-3333-3333-3333-333333333333'];
  cat_ids UUID[];
  b UUID;
  d DATE;
  m INT;
  amt NUMERIC;
  cat UUID;
  emp RECORD;
  wd DATE;
  inv RECORD;
  ret_id UUID;
  cn_id UUID;
  line RECORD;
  return_qty NUMERIC;
  htr_rate NUMERIC;
  ret_taxable NUMERIC;
  ret_cgst NUMERIC;
BEGIN
  SELECT array_agg(category_id) INTO cat_ids FROM expense_categories;

  -- Expenses: monthly recurring (rent, salaries, electricity) + random maintenance/marketing/misc, 9 months back
  FOR b IN SELECT unnest(branch_ids) LOOP
    FOR m IN 0..8 LOOP
      d := (date_trunc('month', CURRENT_DATE) - (m || ' months')::interval)::date + 4;
      INSERT INTO expenses (branch_id, category_id, amount, status, approved_by, created_by, created_at)
      VALUES (b, (SELECT category_id FROM expense_categories WHERE name='Rent'), 45000 + random()*8000, 'APPROVED'::expense_status, 'a0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000002', d::timestamptz);

      INSERT INTO expenses (branch_id, category_id, amount, status, approved_by, created_by, created_at)
      VALUES (b, (SELECT category_id FROM expense_categories WHERE name='Salaries'), 85000 + random()*15000, 'APPROVED'::expense_status, 'a0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000002', d::timestamptz + interval '2 days');

      INSERT INTO expenses (branch_id, category_id, amount, status, approved_by, created_by, created_at)
      VALUES (b, (SELECT category_id FROM expense_categories WHERE name='Electricity'), 6000 + random()*4000, 'APPROVED'::expense_status, 'a0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000002', d::timestamptz + interval '5 days');

      -- a few random smaller expenses per month
      FOR i IN 1..(2 + (random()*3)::int) LOOP
        cat := cat_ids[1 + (random()*(array_length(cat_ids,1)-1))::int];
        amt := 500 + random()*4500;
        INSERT INTO expenses (branch_id, category_id, amount, status, approved_by, created_by, created_at)
        VALUES (b, cat, amt, CASE WHEN random() < 0.85 THEN 'APPROVED' ELSE 'PENDING' END::expense_status,
                CASE WHEN random() < 0.85 THEN 'a0000000-0000-0000-0000-000000000002'::uuid ELSE NULL END,
                'a0000000-0000-0000-0000-000000000002', d::timestamptz + ((random()*25)::int || ' days')::interval);
      END LOOP;
    END LOOP;
  END LOOP;

  -- Attendance: last 60 working days per employee
  FOR emp IN SELECT employee_id, branch_id FROM employees LOOP
    FOR i IN 0..59 LOOP
      wd := CURRENT_DATE - i;
      IF EXTRACT(DOW FROM wd) <> 0 AND random() < 0.93 THEN
        INSERT INTO attendance (employee_id, work_date, check_in, check_out, method)
        VALUES (emp.employee_id, wd, wd::timestamptz + interval '9 hours 30 minutes' + (random()*20||' minutes')::interval,
                wd::timestamptz + interval '20 hours' + (random()*30||' minutes')::interval, 'APP_CHECKIN')
        ON CONFLICT DO NOTHING;
      END IF;
    END LOOP;
  END LOOP;

  -- Leave requests: a handful
  INSERT INTO leave_requests (employee_id, from_date, to_date, status, approved_by)
  SELECT employee_id, CURRENT_DATE + (i*5), CURRENT_DATE + (i*5) + 1,
         (ARRAY['PENDING','APPROVED','APPROVED','REJECTED'])[1+(i%4)],  -- status column is TEXT on leave_requests, no cast needed
         CASE WHEN i%4 <> 0 THEN 'a0000000-0000-0000-0000-000000000001'::uuid ELSE NULL END
  FROM employees, generate_series(1,3) i;

  -- Sales returns: pick ~120 random GST invoices, return one line each with a credit note
  FOR inv IN
    SELECT i.invoice_id, i.branch_id, i.server_received_at
    FROM invoices i WHERE i.invoice_type = 'GST'
    ORDER BY random() LIMIT 120
  LOOP
    SELECT * INTO line FROM invoice_lines WHERE invoice_id = inv.invoice_id ORDER BY random() LIMIT 1;
    IF line IS NULL THEN CONTINUE; END IF;

    ret_id := gen_random_uuid();
    cn_id := gen_random_uuid();

    INSERT INTO credit_notes (credit_note_id, credit_note_number, invoice_id, reason, created_by, created_at)
    VALUES (cn_id, 'CN-' || to_char(inv.server_received_at,'YYYYMM') || '-' || substr(cn_id::text,1,8), inv.invoice_id,
            (ARRAY['Customer changed mind','Wrong item billed','Damaged on delivery','Size mismatch'])[1+floor(random()*4)::int],
            'a0000000-0000-0000-0000-000000000002', inv.server_received_at + interval '2 days');

    INSERT INTO sales_returns (return_id, invoice_id, branch_id, credit_note_id, refund_method, return_reason, created_by, created_at)
    VALUES (ret_id, inv.invoice_id, inv.branch_id, cn_id, (ARRAY['CASH','UPI','CARD'])[1+floor(random()*3)::int]::payment_method,
            'Customer return', 'a0000000-0000-0000-0000-000000000002', inv.server_received_at + interval '2 days');

    return_qty := LEAST(line.qty_in_sale_unit, GREATEST(1, floor(line.qty_in_sale_unit * random())));
    ret_taxable := round((line.taxable_value / line.qty_in_sale_unit) * return_qty, 2);
    ret_cgst := round(ret_taxable * (line.cgst_amount / NULLIF(line.taxable_value,0)), 2);

    INSERT INTO sales_return_lines (return_id, invoice_line_id, qty_base_unit, condition, cash_refund_amount)
    VALUES (ret_id, line.line_id, return_qty, CASE WHEN random() < 0.8 THEN 'RESELLABLE' ELSE 'DAMAGED' END::return_line_condition,
            ret_taxable + 2*ret_cgst);

    INSERT INTO credit_note_lines (credit_note_id, invoice_line_id, qty_base_unit, taxable_value, cgst_amount, sgst_amount)
    VALUES (cn_id, line.line_id, return_qty, ret_taxable, ret_cgst, ret_cgst);

    -- restock resellable returns
    UPDATE branch_stock SET base_unit_qty = base_unit_qty + return_qty WHERE branch_id = inv.branch_id AND product_id = line.product_id;
    INSERT INTO stock_ledger (branch_id, product_id, movement_type, base_unit_qty_change, ref_table, ref_id, created_at)
    VALUES (inv.branch_id, line.product_id, 'SALE_RETURN', return_qty, 'sales_returns', ret_id, inv.server_received_at + interval '2 days');
  END LOOP;

  RAISE NOTICE 'Expenses/HR/Returns seed complete.';
END $$;

-- ============================================================================
-- REMAINING MODULES — procurement, transfers, audits, quotations, warranty
-- ============================================================================
-- These exist so every screen in the app opens onto real rows rather than an
-- empty state, and so each documented edge case (transfer discrepancy, vendor
-- debit note, stock conflict, reserved quotation) has a live example to look at.

DO $$
DECLARE
  b1 UUID := '11111111-1111-1111-1111-111111111111';
  b2 UUID := '22222222-2222-2222-2222-222222222222';
  b3 UUID := '33333333-3333-3333-3333-333333333333';
  owner_id UUID := 'a0000000-0000-0000-0000-000000000001';
  mgr1 UUID := 'a0000000-0000-0000-0000-000000000002';
  inv1 UUID := 'a0000000-0000-0000-0000-000000000008';
  v_po UUID; v_transfer UUID; v_line UUID; v_audit UUID; v_dn UUID;
  v_grn RECORD; v_q UUID; v_cust UUID; v_prod RECORD; v_total NUMERIC;
  v_claim_line RECORD; i INT;
BEGIN
  -- 4.2 batch tracking for shelf-life-sensitive stock (paint/adhesive/chemicals).
  INSERT INTO stock_batches (branch_id, product_id, batch_number, mfg_date, expiry_date, qty_remaining)
  SELECT bs.branch_id, bs.product_id,
         'B' || to_char(CURRENT_DATE - (n * 45), 'YYMM') || '-' || substr(bs.product_id::text, 1, 4),
         CURRENT_DATE - (n * 45), CURRENT_DATE + (540 - n * 45), GREATEST(bs.base_unit_qty / 3, 1)
  FROM branch_stock bs
  JOIN products p ON p.product_id = bs.product_id AND p.batch_tracked
  CROSS JOIN generate_series(0, 2) n;

  -- 4.9 / 12.2 serial tracking for power tools, so a warranty claim can name a unit.
  INSERT INTO stock_serials (branch_id, product_id, serial_number, status)
  SELECT bs.branch_id, bs.product_id,
         'SN-' || upper(substr(md5(bs.branch_id::text || bs.product_id::text || n::text), 1, 10)), 'IN_STOCK'
  FROM branch_stock bs
  JOIN products p ON p.product_id = bs.product_id AND p.serial_tracked
  CROSS JOIN generate_series(1, 5) n
  ON CONFLICT DO NOTHING;

  -- 4.3 / 4.5 auto-suggested purchase orders for whatever is at or below reorder_min.
  FOR i IN 1..3 LOOP
    v_po := gen_random_uuid();
    INSERT INTO purchase_orders (po_id, branch_id, vendor_id, po_number, status, created_by, created_at)
    VALUES (v_po,
            (ARRAY[b1, b2, b3])[i],
            (SELECT vendor_id FROM vendors ORDER BY name LIMIT 1 OFFSET (i - 1)),
            'PO/' || erp_fiscal_year() || '/' || lpad(i::text, 5, '0'),
            (ARRAY['SENT','PARTIALLY_RECEIVED','DRAFT'])[i]::po_status,
            owner_id, now() - (i * 4 || ' days')::interval);

    INSERT INTO purchase_order_lines (po_id, product_id, qty_base_unit, rate)
    SELECT v_po, bs.product_id, GREATEST(COALESCE(bs.reorder_max, 200) - bs.base_unit_qty, 10),
           p.reference_purchase_price
    FROM branch_stock bs
    JOIN products p ON p.product_id = bs.product_id
    WHERE bs.branch_id = (ARRAY[b1, b2, b3])[i]
    ORDER BY bs.base_unit_qty ASC LIMIT 5;
  END LOOP;

  -- 4.5.1 purchase return -> vendor debit note (its own number series), which is
  -- what reverses the ITC claimed on the original GRN.
  FOR v_grn IN SELECT * FROM grn ORDER BY received_at DESC LIMIT 3 LOOP
    v_dn := gen_random_uuid();
    SELECT SUM(gl.qty_base_unit * 0.1 * gl.rate) INTO v_total FROM grn_lines gl WHERE gl.grn_id = v_grn.grn_id;
    INSERT INTO vendor_debit_notes (debit_note_id, debit_note_number, grn_id, vendor_id, branch_id,
                                    reason, total_amount, created_by, created_at)
    VALUES (v_dn, 'DN/' || erp_fiscal_year() || '/' || lpad((floor(random() * 89999) + 10000)::text, 5, '0'),
            v_grn.grn_id, v_grn.vendor_id, v_grn.branch_id,
            (ARRAY['Damaged in transit','Wrong specification supplied','Short shipment'])[1 + floor(random() * 3)::int],
            COALESCE(v_total, 0), inv1, v_grn.received_at + interval '3 days');

    INSERT INTO vendor_debit_note_lines (debit_note_id, grn_line_id, qty_base_unit, rate)
    SELECT v_dn, gl.grn_line_id, round(gl.qty_base_unit * 0.1, 4), gl.rate
    FROM grn_lines gl WHERE gl.grn_id = v_grn.grn_id;

    -- The debit note reduces the payable, mirroring the GRN_PAYABLE entry.
    INSERT INTO vendor_ledger (vendor_id, branch_id, entry_type, amount, ref_table, ref_id, balance_after, created_at)
    VALUES (v_grn.vendor_id, v_grn.branch_id, 'DEBIT_NOTE', -COALESCE(v_total, 0), 'vendor_debit_notes', v_dn,
            COALESCE((SELECT SUM(amount) FROM vendor_ledger WHERE vendor_id = v_grn.vendor_id), 0) - COALESCE(v_total, 0),
            v_grn.received_at + interval '3 days');
  END LOOP;

  -- Some vendor payments, so the payables ageing report is not all one bucket.
  INSERT INTO vendor_ledger (vendor_id, branch_id, entry_type, amount, ref_table, ref_id, balance_after, created_at)
  SELECT v.vendor_id, b1, 'PAYMENT_MADE',
         -round(COALESCE((SELECT SUM(amount) FROM vendor_ledger vl WHERE vl.vendor_id = v.vendor_id), 0) * 0.6, 2),
         'manual', gen_random_uuid(),
         round(COALESCE((SELECT SUM(amount) FROM vendor_ledger vl WHERE vl.vendor_id = v.vendor_id), 0) * 0.4, 2),
         now() - interval '10 days'
  FROM vendors v;

  -- 4.4 inter-branch transfers: one completed cleanly, one still in transit, and
  -- one that arrived short — the TRANSFER_DISCREPANCY case from 4.4.1.
  FOR i IN 1..3 LOOP
    v_transfer := gen_random_uuid();
    INSERT INTO stock_transfers (transfer_id, from_branch_id, to_branch_id, status, transfer_doc_type,
                                 driver_ref, requested_by, dispatched_at, received_at)
    VALUES (v_transfer, b1, (ARRAY[b2, b3, b2])[i],
            (ARRAY['RECEIVED','DISPATCHED','TRANSFER_DISCREPANCY'])[i]::transfer_status,
            'INTRASTATE', 'MH-01-AB-' || (1000 + i), mgr1,
            now() - ((10 - i) || ' days')::interval,
            CASE WHEN i = 2 THEN NULL ELSE now() - ((8 - i) || ' days')::interval END);

    FOR v_prod IN SELECT product_id FROM products ORDER BY random() LIMIT 3 LOOP
      INSERT INTO stock_transfer_lines (transfer_id, product_id, dispatched_qty, received_qty)
      VALUES (v_transfer, v_prod.product_id, 20,
              CASE i WHEN 1 THEN 20 WHEN 2 THEN NULL ELSE 17 END);   -- case 3: 3 units short
    END LOOP;
  END LOOP;

  -- 4.6 physical stock audit with a variance report.
  v_audit := gen_random_uuid();
  INSERT INTO stock_audits (audit_id, branch_id, status, started_at, completed_at, created_by)
  VALUES (v_audit, b1, 'COMPLETED', now() - interval '20 days', now() - interval '19 days', mgr1);
  INSERT INTO stock_audit_lines (audit_id, product_id, system_qty, counted_qty)
  SELECT v_audit, bs.product_id, bs.base_unit_qty,
         GREATEST(bs.base_unit_qty + (random() * 6 - 3)::numeric(14,4), 0)
  FROM branch_stock bs WHERE bs.branch_id = b1 LIMIT 12;

  -- 4.7 damage/wastage write-offs, distinct from a sales return.
  INSERT INTO stock_writeoffs (branch_id, product_id, qty_base_unit, reason_code, created_by, created_at)
  SELECT bs.branch_id, bs.product_id, round((1 + random() * 3)::numeric, 2),
         (ARRAY['DAMAGED','EXPIRED','TRANSFER_LOSS'])[1 + floor(random() * 3)::int], inv1,
         now() - (floor(random() * 60) || ' days')::interval
  FROM branch_stock bs WHERE bs.branch_id IN (b1, b2) ORDER BY random() LIMIT 8;

  -- 5 quotations for B2B/contractor customers, including one with stock actually
  -- reserved (5.1) and one already converted to an invoice.
  FOR i IN 1..6 LOOP
    SELECT customer_id INTO v_cust FROM customers WHERE customer_type = 'B2B_CONTRACTOR' ORDER BY random() LIMIT 1;
    v_q := gen_random_uuid();
    INSERT INTO quotations (quotation_id, quotation_number, branch_id, customer_id, status, price_type,
                            stock_reserved, reservation_hold_until, created_by, created_at)
    VALUES (v_q, 'QT/' || erp_fiscal_year() || '/' || lpad(i::text, 5, '0'),
            (ARRAY[b1, b2, b3])[1 + (i % 3)], v_cust,
            (ARRAY['DRAFT','APPROVED','APPROVED','CONVERTED','EXPIRED','DRAFT'])[i]::quotation_status,
            'TAX_EXCLUSIVE',
            i = 3, CASE WHEN i = 3 THEN now() + interval '3 days' ELSE NULL END,
            mgr1, now() - ((20 - i * 2) || ' days')::interval);

    INSERT INTO quotation_lines (quotation_id, product_id, qty_base_unit, rate)
    SELECT v_q, p.product_id, 10 + floor(random() * 40), pp.selling_price * 0.92   -- contractor tier discount
    FROM products p JOIN product_prices pp ON pp.product_id = p.product_id AND pp.effective_to IS NULL
    ORDER BY random() LIMIT 4;
  END LOOP;

  -- The reserved quotation must actually hold stock, not just claim to (5.1).
  UPDATE branch_stock bs SET reserved_qty = bs.reserved_qty + ql.qty_base_unit
  FROM quotation_lines ql
  JOIN quotations q ON q.quotation_id = ql.quotation_id AND q.stock_reserved
  WHERE bs.product_id = ql.product_id AND bs.branch_id = q.branch_id;

  -- Section 5 delivery challans: goods to site ahead of final billing.
  INSERT INTO delivery_challans (challan_number, quotation_id, branch_id, customer_id, status, created_at)
  SELECT 'DC/' || erp_fiscal_year() || '/' || lpad(row_number() OVER () ::text, 5, '0'),
         q.quotation_id, q.branch_id, q.customer_id, 'DELIVERED', q.created_at + interval '1 day'
  FROM quotations q WHERE q.status IN ('APPROVED','CONVERTED') LIMIT 3;

  INSERT INTO delivery_challan_lines (challan_id, product_id, qty_base_unit)
  SELECT dc.challan_id, ql.product_id, ql.qty_base_unit
  FROM delivery_challans dc JOIN quotation_lines ql ON ql.quotation_id = dc.quotation_id;

  -- 12.2 warranty claims against real sold lines, at various stages of the RMA flow.
  FOR v_claim_line IN
    SELECT il.line_id, p.product_id
    FROM invoice_lines il
    JOIN products p ON p.product_id = il.product_id AND p.serial_tracked
    ORDER BY random() LIMIT 6
  LOOP
    INSERT INTO warranty_claims (invoice_line_id, rma_number, vendor_id, status, claim_date, resolved_at)
    VALUES (v_claim_line.line_id,
            'RMA/' || erp_fiscal_year() || '/' || lpad((floor(random() * 89999) + 10000)::text, 5, '0'),
            'd0000000-0000-0000-0000-000000000004',
            (ARRAY['OPEN','SENT_TO_VENDOR','REPLACED','REPAIRED','REFUNDED','REJECTED'])[1 + floor(random() * 6)::int]::warranty_claim_status,
            CURRENT_DATE - floor(random() * 60)::int,
            CASE WHEN random() < 0.6 THEN now() - (floor(random() * 20) || ' days')::interval ELSE NULL END);
  END LOOP;

  -- 3.5.1 one worked STOCK_CONFLICT so the resolution queue is not empty.
  INSERT INTO stock_conflicts (branch_id, invoice_id, product_id, requested_qty, available_qty, status, created_at)
  SELECT i.branch_id, i.invoice_id, il.product_id, il.base_unit_qty, il.base_unit_qty - 2, 'OPEN',
         i.server_received_at
  FROM invoices i JOIN invoice_lines il ON il.invoice_id = i.invoice_id
  ORDER BY i.server_received_at DESC LIMIT 2;

  -- 6.2 due reminders queued for customers carrying a balance.
  INSERT INTO whatsapp_message_log (customer_id, to_phone, message_type, body, status, queued_at)
  SELECT c.customer_id, c.phone, 'DUE_REMINDER',
         'Reminder: Rs.' || round(l.balance, 2) || ' is outstanding on your account.',
         'QUEUED', now() - interval '1 hour'
  FROM customers c
  JOIN LATERAL (
      SELECT balance_after AS balance FROM customer_credit_ledger
      WHERE customer_id = c.customer_id ORDER BY created_at DESC LIMIT 1
  ) l ON TRUE
  WHERE l.balance > 0 LIMIT 15;

  -- 6.1.1 the offline credit cache each till syncs while it still has a connection.
  INSERT INTO customer_credit_cache (customer_id, cached_credit_limit, cached_balance_owed, cached_at)
  SELECT c.customer_id, c.credit_limit,
         COALESCE((SELECT balance_after FROM customer_credit_ledger
                   WHERE customer_id = c.customer_id ORDER BY created_at DESC LIMIT 1), 0),
         now()
  FROM customers c WHERE c.credit_allowed
  ON CONFLICT (customer_id) DO UPDATE
    SET cached_credit_limit = EXCLUDED.cached_credit_limit,
        cached_balance_owed = EXCLUDED.cached_balance_owed,
        cached_at = EXCLUDED.cached_at;

  -- 7.3 audit trail entries for the sensitive actions the requirement names.
  INSERT INTO audit_log (user_id, branch_id, action, entity_type, entity_id, old_value, new_value, created_at)
  SELECT owner_id, NULL, 'PRICE_CHANGE', 'products', p.product_id,
         jsonb_build_object('selling_price', pp.selling_price),
         jsonb_build_object('selling_price', round(pp.selling_price * 1.05, 2)),
         now() - (floor(random() * 90) || ' days')::interval
  FROM products p JOIN product_prices pp ON pp.product_id = p.product_id AND pp.effective_to IS NULL
  LIMIT 10;

  INSERT INTO audit_log (user_id, branch_id, action, entity_type, entity_id, new_value, created_at)
  SELECT mgr1, b1, 'DISCOUNT_OVERRIDE', 'invoices', i.invoice_id,
         jsonb_build_object('discount_pct', 8, 'approved_by', 'Sunita Rao'),
         i.server_received_at
  FROM invoices i WHERE i.branch_id = b1 ORDER BY random() LIMIT 8;

  INSERT INTO audit_log (user_id, branch_id, action, entity_type, entity_id, new_value, created_at)
  SELECT inv1, b1, 'STOCK_ADJUSTMENT', 'stock_audits', v_audit,
         jsonb_build_object('variance_lines', (SELECT count(*) FROM stock_audit_lines WHERE audit_id = v_audit)),
         now() - interval '19 days';

  RAISE NOTICE 'Module seed complete.';
END $$;

-- ---------------------------------------------------------------------------
-- Level the closing stock position.
--
-- Nine months of simulated selling leaves most shelves near empty, which makes a
-- freshly seeded database look like a shop that has gone out of business. This
-- final pass tops every branch up to a healthy level above its reorder point --
-- and, because stock in this system only ever moves through the ledger, it does
-- so as an explicit COUNT_ADJUSTMENT rather than by writing branch_stock directly.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  r RECORD;
  v_target NUMERIC;
  v_delta  NUMERIC;
  inv_user UUID := 'a0000000-0000-0000-0000-000000000008';
BEGIN
  FOR r IN
    SELECT bs.branch_id, bs.product_id, bs.base_unit_qty, bs.reorder_min, bs.reorder_max,
           p.base_unit
      FROM branch_stock bs JOIN products p ON p.product_id = bs.product_id
  LOOP
    -- Aim between the reorder point and the restock target, with enough spread
    -- that the "needs reordering" screen still has genuine examples on it.
    v_target := CASE
        WHEN random() < 0.12 THEN COALESCE(r.reorder_min, 10) * 0.4      -- a few genuinely low
        ELSE COALESCE(r.reorder_max, 200) * (0.55 + random() * 0.4)
    END;
    IF r.base_unit = 'PIECE' THEN v_target := round(v_target); END IF;
    v_delta := round((v_target - r.base_unit_qty)::numeric, 4);
    CONTINUE WHEN v_delta = 0;

    UPDATE branch_stock SET base_unit_qty = base_unit_qty + v_delta, updated_at = now()
     WHERE branch_id = r.branch_id AND product_id = r.product_id;

    INSERT INTO stock_ledger (branch_id, product_id, movement_type, base_unit_qty_change,
                              ref_table, ref_id, reason_code, created_by, created_at)
    VALUES (r.branch_id, r.product_id, 'COUNT_ADJUSTMENT', v_delta, 'seed', gen_random_uuid(),
            'OPENING_BALANCE_LEVELLING', inv_user, now() - interval '1 hour');
  END LOOP;
  RAISE NOTICE 'Closing stock levelled.';
END $$;

-- ---------------------------------------------------------------------------
-- Align the gapless counters with the history just generated, so the first live
-- document issued after seeding continues the series instead of colliding (3.6).
-- ---------------------------------------------------------------------------
INSERT INTO document_sequences (branch_id, series, fiscal_year, prefix, last_number)
SELECT i.branch_id, 'INVOICE', erp_fiscal_year(now()),
       'INV-' || upper(substr(replace(b.name, ' ', ''), 1, 3)),
       count(*) FILTER (WHERE erp_fiscal_year(i.server_received_at) = erp_fiscal_year(now()))
FROM invoices i JOIN branches b ON b.branch_id = i.branch_id
GROUP BY i.branch_id, b.name
ON CONFLICT (branch_id, series, fiscal_year) DO UPDATE SET last_number = EXCLUDED.last_number;

INSERT INTO document_sequences (branch_id, series, fiscal_year, prefix, last_number)
SELECT b.branch_id, s.series, erp_fiscal_year(now()), s.prefix, s.start_at
FROM branches b CROSS JOIN (VALUES
    ('CREDIT_NOTE','CN', 200),
    ('DEBIT_NOTE','DN', 20),
    ('QUOTATION','QT', 10),
    ('GRN','GRN', 500),
    ('CHALLAN','DC', 10),
    ('TRANSFER','TR', 10),
    ('PO','PO', 10),
    ('RMA','RMA', 10)
) AS s(series, prefix, start_at)
ON CONFLICT (branch_id, series, fiscal_year) DO NOTHING;

ANALYZE;
